# 异常

---

## 异常

### 异常的概述和分类

* A:异常的概述
	* 异常就是Java程序在运行过程中出现的错误。
* B:异常的分类
	* 通过API查看Throwable
	* Error
		* 服务器宕机,数据库崩溃等
	* Exception
C:异常的继承体系
	* Throwable
		* Error
		* Exception
			* RuntimeException

### JVM默认是如何处理异常的

* main函数收到这个问题时,有两种处理方式:
* a:自己将该问题处理,然后继续运行
* b:自己没有针对的处理方式,只有交给调用main的jvm来处理
* jvm有一个默认的异常处理机制,就将该异常进行处理.
* 并将该异常的名称,异常的信息.异常出现的位置打印在了控制台上,同时将程序停止运行

```
public class Demo1_Exception {

	public static void main(String[] args) {
		//demo1();
		Demo d = new Demo();
		int x = d.div(10, 0);
		System.out.println(x);
	}

	public static void demo1() {
		int[] arr = {11,22,33,44,55};
		//arr = null;					
		//NullPointerException 空指针异常

		System.out.println(arr[10]);
		//ArrayIndexOutOfBoundsException	数组索引越界异常
	}
}

class Demo {

	// 除法运算
	public int div(int a,int b) {		//a = 10,b = 0
		return a / b;					
		// 10 / 0 被除数是10,除数是0当除数是0的时候违背了算数运算法则,抛出异常
	   //new ArithmeticException("/ by zero");
	}
}
```

### try...catch的方式处理异常1

* A:异常处理的两种方式
	* a:try…catch…finally
		* try catch
		* try catch finally
		* try finally
		* try:用来检测异常的,catch:用来捕获异常的,finally:释放资源
	* b:throws

* B:try...catch处理异常的基本格式
    * try…catch…finally

* try...catch的方式处理1个异常

```
public class Demo2_Exception {

	//当通过trycatch将问题处理了,程序会继续执行
	public static void main(String[] args) {
		Demo2 d = new Demo2();
		try{
			int x = d.div(10, 0);
			System.out.println(x);
		}catch(ArithmeticException a) {		
		    //ArithmeticException a = new ArithmeticException();
			System.out.println("出错了,除数为零了");
		}
		System.out.println("1111111111111111");
	}
}

class Demo2 {
	public int div(int a,int b) {	//a = 10,b = 0
		return a / b;	//new ArithmeticException("/ by zero");
	}
}
```

### try...catch的方式处理异常2

* try...catch的方式处理多个异常

* try后面如果跟多个catch,那么小的异常放前面,大的异常放后面,根据多态的原理,如果大的放前面,就会将所有的子类对象接收,后面的catch就没有意义了

```
public static void demo1() {
	int a = 10;
	int b = 0;
	int[] arr = {11,22,33,44,55};

	try {
		System.out.println(a / b);
		System.out.println(arr[10]);
		arr = null;
		System.out.println(arr[0]);
	} catch (ArithmeticException e) {
		System.out.println("除数不能为零");
	} catch (ArrayIndexOutOfBoundsException e) {
		System.out.println("索引越界了");
	} catch (Exception e) {	 //Exception e = new NullPointerException();
		System.out.println("出错了");
	}

	System.out.println("over");
}
```

* JDK7以后处理多个异常的方式及注意事项

```
//JDK7如何处理多个异常
try {
	System.out.println(a / b);
	System.out.println(arr[10]);
} catch (ArithmeticException | ArrayIndexOutOfBoundsException e) {
	System.out.println("出错了");
}
```

### 编译期异常和运行期异常的区别

* 编译期异常和运行期异常的区别
	* Java中的异常被分为两大类：编译时异常和运行时异常。
	* 所有的RuntimeException类及其子类的实例被称为运行时异常，其他的异常就是编译时异常

	* 编译时异常
		* Java程序必须显示处理，否则程序就会发生错误，无法通过编译,在编译某个程序的时候,有可能会有这样那样的事情发生,比如文件找不到,这样的异常就必须在编译的时候处理
		如果不处理编译通不过

		```
		try {
			FileInputStream fis = new FileInputStream("xxx.txt");
		} catch(Exception e) {
		```

	* 运行时异常
		* 无需显示处理，也可以和编译时异常一样处理,就是程序员所犯得错误,需要回来修改代码

### Throwable的几个常见方法

* Throwable的几个常见方法
	* a:getMessage()
		* 获取异常信息，返回字符串。
	* b:toString()
		* 获取异常类名和异常信息，返回字符串。
	* c:printStackTrace()
		* 获取异常类名和异常信息，以及异常出现在程序中的位置。返回值void。

```
public static void main(String[] args) {
	try {
		System.out.println(1/0);
	} catch (Exception e) {
	//Exception e = new ArithmeticException("/ by zero");

	    //System.out.println(e.getMessage());	//获取异常信息

		//调用toString方法,打印异常类名和异常信息
		System.out.println(e);

	    //jvm默认就用这种方式处理异常
		e.printStackTrace();		
	}
}
```

### throws的方式处理异常


* 定义功能方法时，需要把出现的问题暴露出来让调用者去处理。
* 那么就通过throws在方法上标识。
* 编译时异常的抛出必须对其进行处理
* 运行时异常的抛出可以处理也可以不处理

```
package com.heima.exception;

public class Demo {
	public static void main(String[] args) throws Exception {
		Person p = new Person();
		p.setAge(-17);
		System.out.println(p.getAge());
	}
}

class Person {
	private String name;
	private int age;
    //构造，set，get方法
	public void setAge(int age) throws Exception {
		if(age >0 && age <= 150) {
			this.age = age;
		}else {
			throw new Exception("年龄非法");
		}
	}


}
```

### throw的概述以及和throws的区别

* throw的概述
	* 在功能方法内部出现某种情况，程序不能继续运行，需要进行跳转时，就用throw把异常对象抛出。

* throws和throw的区别
	* a:throws
		* 用在方法声明后面，跟的是异常类名
		* 可以跟多个异常类名，用逗号隔开
		* 表示抛出异常，由该方法的调用者来处理
	* b:throw
		* 用在方法体内，跟的是异常对象名
		* 只能抛出一个异常对象名
		* 表示抛出异常，由方法体内的语句处理

### finally关键字的特点及作用

* finally的特点
	* 被finally控制的语句体一定会执行
	* 特殊情况：在执行到finally之前jvm退出了(比如System.exit(0))
* finally的作用
	* 用于释放资源，在IO流操作和数据库操作中会见到

```
public static void main(String[] args) {
	try {
		System.out.println(10/0);
	} catch (Exception e) {
		System.out.println("除数为零了");
		System.exit(0);		//退出jvm虚拟机,finally就不执行啦
		return;
		/**
		    return语句相当于是方法的最后一口气,那么在他将死之前会看 一看有没有finally帮其完成遗愿,如果有就将finally执行后在彻底返回
		*/
	} finally {
		System.out.println("看看我执行了吗");
	}
}
```

### finally关键字的面试题

* 面试题1：final,finally和finalize的区别
    * final可以修饰类,不能被继承；修饰方法,不能被重写；修饰变量,只能赋值一次
	* finally是try语句中的一个语句体,不能单独使用,用来释放资源
	* finalize是一个方法,当垃圾回收器确定不存在对该对象的更多引用时，由对象的垃圾回收器调用此方法。

* 面试题2：如果catch里面有return语句，请问finally的代码还会执行吗?如果会，请问是在return前还是return后。

会执行，建立了返回路径，但是没有返回，去执行finally，然后彻底返回

千万不要在finally里面写返回语句,因为finally的作用是为了释放资源,是肯定会执行的，如果在这里面写返回语句,那么try和catch的结果都会被改变,所以这么写就是犯罪

```
public static void main(String[] args) {
		System.out.println(d.method());
	}

public int method() {
    int x = 10;
    try {
    	x = 20;
    	System.out.println(1/0);
    	return x;
    } catch (Exception e) {
    	x = 30;
    	return x;
    } finally {
    	x = 40;
    	//return x;					
    }
}
```

### 自定义异常概述和基本使用

* 为什么需要自定义异常
    * 通过名字区分到底是神马异常,有针对的解决办法
	* 举例：人的年龄
* B:自定义异常概述
	* 继承自Exception
	* 继承自RuntimeException

```
//年龄
class AgeOutOfBoundsException extends Exception {

	public AgeOutOfBoundsException() {
		super();
	}

	public AgeOutOfBoundsException(String message) {
		super(message);
	}
}

class Person {
    private int age;

	//构造，set，get方法

	public void setAge(int age) throws AgeOutOfBoundsException {
		if(age >0 && age <= 150) {
			this.age = age;
		}else {
			throw new AgeOutOfBoundsException("年龄非法");
		}
	}
}


```

### 异常的注意事项及如何使用异常处理

* 异常注意事项
	* a:子类重写父类方法时，子类的方法必须抛出相同的异常或父类异常的子类。(父亲坏了,儿子不能比父亲更坏)
	* b:如果父类抛出了多个异常,子类重写父类时,只能抛出相同的异常或者是他的子集,子类不能抛出父类没有的异常
	* c:如果被重写的方法没有异常抛出,那么子类的方法绝对不可以抛出异常,如果子类方法内有异常发生,那么子类只能try,不能throws

* 如何使用异常处理
	* 原则:如果该功能内部可以将问题处理,用try,如果处理不了,交由调用者处理,这是用throws
	* 区别:
		* 后续程序需要继续运行就try
		* 后续程序不需要继续运行就throws
	* 如果JDK没有提供对应的异常，需要自定义异常。

### 异常练习

* 键盘录入一个int类型的整数,对其求二进制表现形式
	 * 如果录入的整数过大,给予提示,录入的整数过大请重新录入一个整数BigInteger
	 * 如果录入的是小数,给予提示,录入的是小数,请重新录入一个整数
	 * 如果录入的是其他字符,给予提示,录入的是非法字符,请重新录入一个整数
* 分析:
	 * 1,创建键盘录入对象
	 * 2,将键盘录入的结果存储在String类型的字符串中,存储int类型中如果有不符合条件的直接报错,无法进行后续判断
	 * 3,键盘录入的结果转换成int类型的数据,是正确的还是错误的
	 * 4,正确的直接转换
	 * 5,错误的要进行对应判断

```
public static void main(String[] args) {
	Scanner sc = new Scanner(System.in);
	System.out.println("请输入一个整数:");

	while(true) {
	    //将键盘录入的结果存储在line中
		String line = sc.nextLine();					

		try {
			int num = Integer.parseInt(line);//将字符串转换为整数

			//将整数转换为二进制
			System.out.println(Integer.toBinaryString(num));
			break;	//跳出循环
		}catch(Exception e) {
			try {
				new BigInteger(line);
				System.out.println("录入错误,您录入的是一个过大整数,请重新输入一个整数:");
			}catch (Exception e2) {							
			    //alt + shif + z (try catch快捷键)
				try {
					new BigDecimal(line);					System.out.println("录入错误,您录入的是一个小数,请重新输入一个整数:");
				} catch (Exception e1) {					System.out.println("录入错误,您录入的是非法字符,请重新输入一个整数:");
				}
			}
		}
	}
}
```

## Throwable

### 概括

* Throwable是java.lang包中一个专门用来处理异常的类。它有两个子类，即Error 和Exception，它们分别用来处理两组异常。
* Error用来处理程序运行环境方面的异常，比如，虚拟机错误、装载错误和连接错误，这类异常主要是和硬件有关的，而不是由程序本身抛出的。
* Exception是Throwable的一个主要子类。Exception下面还有子类，其中一部分子类分别对应于Java程序运行时常常遇到的各种异常的处理，其中包括隐式异常。比如，程序中除数为0引起的错误、数组下标越界错误等，这类异常也称为运行时异常，因为它们虽然是由程序本身引起的异常，但不是程序主动抛出的，而是在程序运行中产生的。Exception子类下面的另一部分子类对应于Java程序中的非运行时异常的处理（在下图中将它们直接属于Exception了），这些异常也称为显式异常。它们都是在程序中用语句抛出、并且也是用语句进行捕获的，比如，文件没找到引起的异常、类没找到引起的异常等。

### 一些主要子类对应的异常处理功能简要说明如下：
* ArithmeticException——由于除数为0引起的异常；

* ArrayStoreException——由于数组存储空间不够引起的异常；

* ClassCastException—一当把一个对象归为某个类，但实际上此对象并不是由这个类 创建的，也不是其子类创建的，则会引起异常；

* IllegalMonitorStateException——监控器状态出错引起的异常；

* NegativeArraySizeException—一数组长度是负数，则产生异常；

* NullPointerException—一程序试图访问一个空的数组中的元素或访问空的对象中的 方法或变量时产生异常；

* OutofMemoryException——用new语句创建对象时，如系统无法为其分配内存空 间则产生异常；

* SecurityException——由于访问了不应访问的指针，使安全性出问题而引起异常；

* IndexOutOfBoundsExcention——由于数组下标越界或字符串访问越界引起异常；

* IOException——由于文件未找到、未打开或者I/O操作不能进行而引起异常；

* ClassNotFoundException——未找到指定名字的类或接口引起异常；

* CloneNotSupportedException——一程序中的一个对象引用Object类的clone方法，但 此对象并没有连接Cloneable接口，从而引起异常；

* InterruptedException—一当一个线程处于等待状态时，另一个线程中断此线程，从 而引起异常，有关线程的内容，将在下一章讲述；

* NoSuchMethodException一所调用的方法未找到，引起异常；

* Illega1AccessExcePtion—一试图访问一个非public方法；

* StringIndexOutOfBoundsException——访问字符串序号越界，引起异常；

* ArrayIdexOutOfBoundsException—一访问数组元素下标越界，引起异常；

* NumberFormatException——字符的UTF代码数据格式有错引起异常；

* IllegalThreadException—一线程调用某个方法而所处状态不适当，引起异常；

* FileNotFoundException——未找到指定文件引起异常；

* EOFException——未完成输入操作即遇文件结束引起异常。

### Throwable原码解析

```
package java.lang;  
import java.io.*;  
/**
*  
* Throwable是所有Error和Exceptiong的父类
* 注意它有四个构造函数:
* Throwable()
* Throwable(String message)
* Throwable(Throwable cause)
* Throwable(String message, Throwable cause)
*  
*/  
public class Throwable implements Serializable {  
      private static final long serialVersionUID = -3042686055658047285L;  

      /**
       * Native code saves some indication of the stack backtrace in this slot.
       */  
      private transient Object backtrace;   

      /**
       * 描述此异常的信息
       */  
      private String detailMessage;  

      /**
       * 表示当前异常由那个Throwable引起
        * 如果为null表示此异常不是由其他Throwable引起的
        * 如果此对象与自己相同,表明此异常的起因对象还没有被初始化
       */  
      private Throwable cause = this;  

      /**
       * 描述异常轨迹的数组
       */  
      private StackTraceElement[] stackTrace;  

      /**
       * 构造函数,起因对象没有被初始化可以在以后使用initCause进行初始化
        * fillInStackTrace可以用来初始化它的异常轨迹的数组
       */  
      public Throwable() {  
          fillInStackTrace();  
      }  

      /**
       * 构造函数
       */  
      public Throwable(String message) {  
         //填充异常轨迹数组  
          fillInStackTrace();  
         //初始化异常描述信息  
          detailMessage = message;  
      }  

      /**
       * 构造函数,cause表示起因对象
       */  
      public Throwable(String message, Throwable cause) {  
          fillInStackTrace();  
          detailMessage = message;  
          this.cause = cause;  
      }  

      /**
       * 构造函数
       */  
      public Throwable(Throwable cause) {  
          fillInStackTrace();  
          detailMessage = (cause==null ? null : cause.toString());  
          this.cause = cause;  
      }  

      /**
       * 获取详细信息
       */  
      public String getMessage() {  
          return detailMessage;  
      }  

      /**
       * 获取详细信息
       */  
      public String getLocalizedMessage() {  
          return getMessage();  
      }  

      /**
       * 获取起因对象
       */  
      public Throwable getCause() {  
          return (cause==this ? null : cause);  
      }  

      /**
       * 初始化起因对象,这个方法只能在未被初始化的情况下调用一次
       */  
      public synchronized Throwable initCause(Throwable cause) {  
         //如果不是未初始化状态则抛出异常  
          if (this.cause != this)  
              throw new IllegalStateException("Can't overwrite cause");  

        //要设置的起因对象与自身相等则抛出异常  
          if (cause == this)  
              throw new IllegalArgumentException("Self-causation not permitted");  

         //设置起因对象  
          this.cause = cause;  
         //返回设置的起因的对象  
          return this;  
      }  

      /**
       * 字符串表示形式
       */  
      public String toString() {       
          String s = getClass().getName();          
          String message = getLocalizedMessage();        
          return (message != null) ? (s + ": " + message) : s;  
      }  

      /**
       * 打印出错误轨迹
       */  
      public void printStackTrace() {   
          printStackTrace(System.err);  
      }  

      /**
       * 打印出错误轨迹
       */  
      public void printStackTrace(PrintStream s) {  
          synchronized (s) {  
            //调用当前对象的toString方法  
              s.println(this);  
            //获取异常轨迹数组  
              StackTraceElement[] trace = getOurStackTrace();  

            //打印出每个元素的字符串表示  
              for (int i=0; i < trace.length; i++)  
                s.println("\tat " + trace[i]);  

            //获取起因对象  
              Throwable ourCause = getCause();  

            //递归的打印出起因对象的信息  
              if (ourCause != null)  
                ourCause.printStackTraceAsCause(s, trace);  
          }  
      }  

      /**
       * 打印起因对象的信息
       * @param s 打印的流
        * @param causedTrace 有此对象引起的异常的异常轨迹  
       */  
      private void printStackTraceAsCause(PrintStream s,  
                                          StackTraceElement[] causedTrace)  
      {  
         //获得当前的异常轨迹  
          StackTraceElement[] trace = getOurStackTrace();  
         //m为当前异常轨迹数组的最后一个元素位置,   
         //n为当前对象引起的异常的异常轨迹数组的最后一个元素  
          int m = trace.length-1, n = causedTrace.length-1;  
         //分别从两个数组的后面做循环,如果相等则一直循环,直到不等或数组到头  
          while (m >= 0 && n >=0 && trace[m].equals(causedTrace[n])) {  
              m--; n--;  
         }  

         //相同的个数  
          int framesInCommon = trace.length - 1 - m;  

         //打印出不同的错误轨迹  
          s.println("Caused by: " + this);  
          for (int i=0; i <= m; i++)  
              s.println("\tat " + trace[i]);  
          //如果有相同的则打印出相同的个数  
          if (framesInCommon != 0)  
              s.println("\t... " + framesInCommon + " more");  

         //获得此对象的起因对象,并递归打印出信息  
          Throwable ourCause = getCause();  
          if (ourCause != null)  
              ourCause.printStackTraceAsCause(s, trace);  
      }  

      /**
       * 打印出错误轨迹
       */  
      public void printStackTrace(PrintWriter s) {   
          synchronized (s) {  
              s.println(this);  
              StackTraceElement[] trace = getOurStackTrace();  
              for (int i=0; i < trace.length; i++)  
                  s.println("\tat " + trace[i]);  

              Throwable ourCause = getCause();  
              if (ourCause != null)  
                  ourCause.printStackTraceAsCause(s, trace);  
          }  
      }  

      /**
       * 打印起因对象的信息
        */  
      private void printStackTraceAsCause(PrintWriter s,  
                                          StackTraceElement[] causedTrace)  
      {  
          // assert Thread.holdsLock(s);  

          // Compute number of frames in common between this and caused  
          StackTraceElement[] trace = getOurStackTrace();  
          int m = trace.length-1, n = causedTrace.length-1;  
          while (m >= 0 && n >=0 && trace[m].equals(causedTrace[n])) {  
              m--; n--;  
          }  
          int framesInCommon = trace.length - 1 - m;  

          s.println("Caused by: " + this);  
          for (int i=0; i <= m; i++)  
              s.println("\tat " + trace[i]);  
          if (framesInCommon != 0)  
              s.println("\t... " + framesInCommon + " more");  

          // Recurse if we have a cause  
          Throwable ourCause = getCause();  
      if (ourCause != null)  
              ourCause.printStackTraceAsCause(s, trace);  
      }  

      /**
       * 填充异常轨迹
       */  
      public synchronized native Throwable fillInStackTrace();  

      /**
       * 返回当前的异常轨迹的拷贝
       */  
      public StackTraceElement[] getStackTrace() {  
          return (StackTraceElement[]) getOurStackTrace().clone();  
      }  


      /**
       * 获取当前的异常轨迹
        */  
  private synchronized StackTraceElement[] getOurStackTrace() {  
         //如果第一次调用此方法则初始化异常轨迹数组  
          if (stackTrace == null) {  
            //获得异常轨迹深度  
              int depth = getStackTraceDepth();  
            //创建新的异常轨迹数组,并填充它  
              stackTrace = new StackTraceElement[depth];  

            for (int i=0; i < depth; i++)  
                stackTrace[i] = getStackTraceElement(i);//获取指定位标的异常轨迹  
          }  

          return stackTrace;  
      }  

      /**
       * 设置异常轨迹
       */  
      public void setStackTrace(StackTraceElement[] stackTrace) {  
         //拷贝设置参数  
          StackTraceElement[] defensiveCopy =  
              (StackTraceElement[]) stackTrace.clone();  

         //如果设置参数有空元素则抛出异常  
          for (int i = 0; i < defensiveCopy.length; i++)  
              if (defensiveCopy[i] == null)  
                  throw new NullPointerException("stackTrace[" + i + "]");  

         //设置当前对象的异常轨迹  
          this.stackTrace = defensiveCopy;  
      }  

      /**
       * 异常轨迹的深度,0表示无法获得
       */  
      private native int getStackTraceDepth();  

      /**
       * 获取指定位标的异常轨迹
       */  
      private native StackTraceElement getStackTraceElement(int index);  


      private synchronized void writeObject(java.io.ObjectOutputStream s)  
          throws IOException  
      {  
          getOurStackTrace();  
          s.defaultWriteObject();  
      }  
}  


```
